const ICONS = {
  배민: {
    ACTIVE_DOT: "/baemin/active_dot.png",
    APP_DOWNLOAD: "/baemin/app_download.png",
    APP_STORE: "/baemin/appstore.png",
    GOOGLE_PLAY: "/baemin/googleplay.png",
    ICON_BLOG: "/baemin/iconBlog.png",
    ICON_FACEBOOK: "/baemin/iconFacebook.png",
    ICON_INSTAGRAM: "/baemin/iconInstagram.png",
    ICON_YOUTUBE: "/baemin/iconYoutube.png",
    INACTIVE_DOT: "/baemin/inactive_dot.png",
    LANDING2_IMAGE: "/baemin/landing2_image.png",
    LANDING2_TEXT: "/baemin/landing2_text.png",
    LANDING3_IMAGE: "/baemin/landing3_image.png",
    LANDING3_TEXT: "/baemin/landing3_text.png",
    LANDING4_IMAGE: "/baemin/landing4_image.png",
    LANDING4_TEXT: "/baemin/landing4_text.png",
    LANDING5_IMAGE: "/baemin/landing5_image.png",
    LANDING5_TEXT: "/baemin/landing5_text.png",
    LANDING6_IMAGE: "/baemin/landing6_image.png",
    LANDING6_TEXT: "/baemin/landing6_text.png",
    LANDING7_IMAGE: "/baemin/landing7_image.png",
    LANDING7_TEXT: "/baemin/landing7_text.png",
    LANDING8_IMAGE: "/baemin/landing8_image.png",
    LANDING8_TEXT: "/baemin/landing8_text.png",
    LANDING9_IMAGE: "/baemin/landing9_image.png",
    LANDING9_TEXT: "/baemin/landing9_text.png",
    LOGO: "/baemin/logo.png",
    MAIN_TEXT_01: "/baemin/main_text_01.png",
    MAIN_TEXT_02: "/baemin/main_text_02.png",
    MAIN_TEXT_03: "/baemin/main_text_03.png",
    MAIN_TEXT_04: "/baemin/main_text_04.png",
    MAIN_TEXT_05: "/baemin/main_text_05.png",
    MAIN_01: "/baemin/main01.jpg",
    MAIN_02: "/baemin/main02.jpg",
    MAIN_03: "/baemin/main03.jpg",
    MAIN_04: "/baemin/main04.jpg",
    MAIN_05: "/baemin/main05.jpg",
    QR_CODE: "/baemin/qrcode.png",
    RIDER_BUTTON: "/baemin/riderButton.png",
    SCROLL: "/baemin/scroll.png",
    THUMBNAIL: "/baemin/thumbnail.png",
  },
};

export default ICONS;
